# Generated by Django 5.1.2 on 2024-10-27 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horarios'),
        ),
    ]
