# Generated by Django 5.1.2 on 2024-10-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_horarios_alter_agendamentos_horario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Horarios',
            new_name='Horario',
        ),
    ]
