# Generated by Django 5.1.2 on 2024-10-27 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_horarios_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='profissional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.profissional'),
        ),
    ]
