# Generated by Django 5.1.2 on 2024-10-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_horario_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='horario',
        ),
    ]
