# Generated by Django 5.1.2 on 2024-10-27 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_agendamentos_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
