# Generated by Django 5.1.2 on 2024-10-27 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_horarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='data',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.horarios'),
        ),
        migrations.AlterField(
            model_name='horarios',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
