# Generated by Django 5.1.2 on 2024-10-27 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_agendamentos_data_agendamentos_horario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='horario',
        ),
        migrations.DeleteModel(
            name='Horarios',
        ),
    ]
