# Generated by Django 5.1.2 on 2024-11-02 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_profissional_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ocupacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.ocupacao'),
        ),
    ]
