# Generated by Django 5.1.2 on 2024-11-05 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_horario_ocupacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ocupacao',
        ),
    ]
